### ISSUE TITLE
Update URLs for Swedish instance

### ISSUE THREAD

**Issue by shahmanash** [raymondben/livingatlases#1]
{"max_occurrence_records": 500000,
 "server_max_url_length": 8150,
 "base_url_spatial": "https://spatial.bioatlas.se/ws/",
 "base_url_bie": "https://species.bioatlas.se/ws/",
 "base_url_biocache": "https://records.bioatlas.se/ws/",
 "base_url_biocache_download" = "https://records.bioatlas.se/ws/biocache-download/",
 "biocache_version": "2.2.3",
 "base_url_alaspatial": "https://spatial.bioatlas.se/ws/",
 "base_url_images": "https://images.bioatlas.se/",
 "base_url_logger": "https://logger.bioatlas.se/service/logger/",
 #"base_url_fieldguide": "http://fieldguide.ala.org.au/",
 "base_url_lists": "https://lists.bioatlas.se/ws/"
}

**Comment by raymondben** [comment]
Updated, thanks! https://github.com/raymondben/livingatlases/commit/3b7c18af6af3b2b8d00c62b212d5bec636e1b220
